name: sharpvisions_task
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.10.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.6.2
  provider: ^6.1.5+1
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  get_it: ^9.2.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.3
  skeletonizer: ^2.1.2
  infinite_scroll_pagination: ^4.1.0
  flutter_secure_storage: ^10.0.0
  fast_cached_network_image: ^1.3.3+5
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  retrofit: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  retrofit_generator: ^10.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
